---
- hosts: allinone
  vars_files:
    - vars/main.yml
  tasks: []
  # pre_tasks: 
  roles:
    - { role: ensure-default-dns }
    - { role: get-ipaddress }
    - { role: docker-install }
    - { role: dougbtv.kpm-install , kpm_version: "v0.21.2" }
    - { role: openshift-install }
    - { role: openshift-up }
    - { role: iptables-config }
    # kpm-registry role is required for roles which look at the registry
    - { role: kpm-registry } 
    - { role: openshift-aio-dns-hack }
    # other options: skip_kpm_push: true, stackanetes_teardown: true
    - { role: stackanetes-configure, force_kpm_push: true } 
    - { role: stackanetes-routing }
  post_tasks:
    - debug:
        msg: |
          Here's an example /etc/hosts file
          {{ example_etc_hosts }}

    - debug: 
        msg: "The KPM registry is @ {{ kpm_registry_url }}"