---
- hosts: allinone
  vars_files:
    - vars/main.yml
  tasks: []
  pre_tasks: 
    - name: Install facter
      yum:
        name: facter
        state: present

    - name: Get IP address with facter
      shell: >
        facter {{ facter_ipaddress }}
      register: facter_result

    - name: Set IP address as fact
      set_fact: 
        main_ip_address: "{{ facter_result.stdout}}"
  roles:
    # - { role: docker-install }
    # - { role: dougbtv.kpm-install , kpm_version: "v0.21.2" }
    # - { role: openshift-install }
    # - { role: openshift-up }
    
    # This is required for roles which look at the registry.... (as it gets the URL and sets it as a fact.)
    - { role: kpm-registry }
    
    # - { role: openshift-aio-dns-hack }
    
    # - { role: stackanetes-configure, stackanetes_teardown: true }
    # skip the (sometimes time consuming) push with: skip_kpm_push: true
    - { role: stackanetes-configure, skip_kpm_push: true }