---
# Create routes for stackanetes & configure /etc/hosts

- name: Switch to openstack project every time.
  shell: >
    oc project {{ stackanetes_namespace }}

- name: Look for a router pod
  shell: > 
    kubectl get pods --all-namespaces
  register: all_pods

- name: Add hostnetwork policy to router SCC
  shell: >
    oc adm policy add-scc-to-user hostnetwork -z router
  when: "'router' not in all_pods.stdout"

- name: If we don't see a router pod, create router pod (right in the stackanetes namespace, for now.)
  shell: >
    oc adm router
  when: "'router' not in all_pods.stdout"

- name: Get stackanetes routes
  shell: >
    oc get routes
  register: stackanetes_routes

- name: Create route for each stackanetes domain
  shell: >
    oc expose service/traefik --name=traefik.{{ item }} --hostname={{ item }}
  when: "'{{ item }}' not in stackanetes_routes.stdout"
  with_items: "{{stackanetes_domains}}"

- name: Create /etc/hosts entries
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "{{ main_ip_address }} {{ item }}"
    line: "{{ main_ip_address }} {{ item }}"
  with_items: "{{stackanetes_domains}}"

- name: Collect the /etc/hosts entries
  shell: >
    cat /etc/hosts | grep cluster
  register: etc_hosts

- name: Set etc hosts collection as a fact to show later.
  set_fact: 
    example_etc_hosts: "{{ etc_hosts.stdout }}"