---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install facter
  yum:
    name: facter
    state: present

- name: Get IP address with facter
  shell: >
    facter {{ facter_ipaddress }}
  register: facter_result

- name: Set IP address as fact
  set_fact: 
    main_ip_address: "{{ facter_result.stdout}}"