---
- include: bootstrap.yml
  when: "bootstrap_kpm_registry"

- name: Check if registry is up
  shell: >
    oc projects -q
  register: oc_projects

- name: Create kpm namespace
  shell: >
    oc new-project kpm
  when: "'kpm' not in oc_projects.stdout"
  register: kpm_namespace

# - name: check oc projects
#   shell: >
#     oc projects
#   register: check

- name: Set anyuid role to kpm service account
  shell: >
    oc adm policy add-scc-to-user anyuid -z default
  when: kpm_namespace.changed

- name: Add the admin role to the admin user for the kpm namespace
  shell: >
    oc policy add-role-to-user admin admin -n kpm
  when: kpm_namespace.changed

- name: Check for kpm anyuid
  shell: >
    oc export scc anyuid
  register: scc_anyuid
  when: kpm_namespace.changed

# - debug: "msg={{ scc_anyuid }}"

- name: Fail when kpm anyuid scc isn't present
  fail:
    msg: Somehow kpm anyuid scc isn't on the kpm service account
  when: "scc_anyuid.changed and 'kpm' not in scc_anyuid.stdout"

- name: Bring up registry
  shell: > 
    kpm deploy coreos/kpm-registry --namespace kpm -H {{ bootstrap_kpm_registry_uri }}
  when: kpm_namespace.changed

- name: Always switch to kpm namespace
  command: >
    oc project kpm

- name: Wait until all etcd pods are running
  shell: > 
    oc get pods | grep -P "etcd.+Running" | wc -l
  register: etcd_pods_running
  ignore_errors: yes
  until: "'3' in etcd_pods_running.stdout and etcd_pods_running.rc == 0"
  retries: 60
  delay: 2

- name: Wait until the kpm-registry pod is running
  shell: > 
    oc get pods | grep -P "registry.+Running" | wc -l
  register: kpm_pods_running
  ignore_errors: yes
  until: "'1' in kpm_pods_running.stdout and kpm_pods_running.rc == 0"
  retries: 60
  delay: 2

- name: Get kpm registry pod name
  shell: >
    oc get pods | awk '/kpm-registry/ {print $1}'
  register: kpm_pod_name

- name: Get kpm cluster URL
  shell: >
    oc describe pod {{ kpm_pod_name.stdout }} | grep KPM_URI | awk '{print $2}' | perl -p -i -e 's|^https?://(.+)$|$1|'
  register: kpm_cluster_url
  until: "'cluster' in kpm_cluster_url.stdout"
  retries: 15
  delay: 2

# - shell: exit 1
#   register: task_result
#   ignore_errors: yes

- name: Set kpm cluster URL as fact
  set_fact: 
    kpm_registry_url: "{{ kpm_cluster_url.stdout }}"

- debug:
    msg: "The KPM registry is @ {{ kpm_registry_url }}"

- include: bootstrap-cleanup.yml
  when: "bootstrap_kpm_registry"
