--- 
# install-openstack-clients
# installs openstack clients.

- name: Make sure pip is installed
  yum:
    name: python-pip
    state: present

- name: pip install openstack clients
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - python-openstackclient
    - python-neutronclient